### ISSUE TITLE
NameError: name 'METRIC_SYSTEM' is not defined

### ISSUE THREAD

**Issue by tarheelz** [L1p0-M/ha-climacell-weather#2]
No good deed goes unpunished.  I messed you up.  Now climacell will not fire up for me.  (Reverted to 2.06 and it runs.)

```
Log Details (ERROR)
Logger: homeassistant.components.sensor
Source: custom_components/climacell_custom/sensor.py:112
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 11:36:43 PM (1 occurrences)
Last logged: 11:36:43 PM

Error while setting up climacell_custom platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/climacell_custom/sensor.py", line 112, in setup_platform
    elif hass.config.units is METRIC_SYSTEM:
NameError: name 'METRIC_SYSTEM' is not defined
```

**Comment by tarheelz** [comment]
Update:  Same error but now with update to 2022.11.3 it's not fatal

```
Log Details (ERROR)
Logger: homeassistant.components.sensor
Source: custom_components/climacell_custom/sensor.py:112
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 9:22:40 PM (1 occurrences)
Last logged: 9:22:40 PM

Error while setting up climacell_custom platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/climacell_custom/sensor.py", line 112, in setup_platform
    elif hass.config.units is METRIC_SYSTEM:
NameError: name 'METRIC_SYSTEM' is not defined
```

**Comment by L1p0-M** [comment]
Can you test the latest (2.0.8) version?

**Comment by tarheelz** [comment]
Working great.  Thanks!
